/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesTabelas;
import Interfaces.Livros;
import com.mycompany.codigo.Implementacao;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jeova
 */
public class InterfaceLivros extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceLivros
     */
    
    private static DefaultTableModel modelo;
    public InterfaceLivros() throws SQLException {
        initComponents();
        BtnApagar.setEnabled(false);
        BtnAtualizar.setEnabled(false);
        String[] colunas = {"Titulo", "Genero", "ISBN", "Editora", "Autor", "AnoPublicacao", "Quantidade Disponivel", "Numero_paginas", "Nome_Prateleira", "linha", "coluna"};
        modelo = new DefaultTableModel(colunas, 0);
        
        jTable1.setModel(modelo);
        Preencher_tabela("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnAtualizar = new javax.swing.JToggleButton();
        BtnApagar = new javax.swing.JToggleButton();
        BtnCadastrar = new javax.swing.JToggleButton();
        btnPesquisar = new javax.swing.JToggleButton();
        TXTShearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Genero", "ISBN", "Editora", "Autor", "Ano de Publicação", "Quantidade disponivel", "Numero de Paginas", "Nome Pratileira", "Linha", "Coluna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BtnAtualizar.setText("Atualizar");

        BtnApagar.setText("Apagar");
        BtnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnApagarActionPerformed(evt);
            }
        });

        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(BtnApagar)
                                .addGap(18, 18, 18)
                                .addComponent(BtnAtualizar)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TXTShearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisar)
                                .addGap(108, 108, 108))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTShearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        Livros l = new Livros();
        l.setVisible(true);
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void BtnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnApagarActionPerformed
        int selected = jTable1.getSelectedRow();
        String Titulo = (String) jTable1.getValueAt(selected, 0);
        String Genero = (String) jTable1.getValueAt(selected, 1);
        String ISBN = (String) jTable1.getValueAt(selected, 2);
        String Editora = (String) jTable1.getValueAt(selected, 3);
        String Ano = (String) jTable1.getValueAt(selected, 5);
        String Autor = (String) jTable1.getValueAt(selected, 4);
        String Quant = (String) jTable1.getValueAt(selected, 6);
        String Num_page = (String) jTable1.getValueAt(selected, 7);
        String Prat = (String) jTable1.getValueAt(selected, 8);
        String Linha = (String) jTable1.getValueAt(selected, 9);
        String Coluna = (String) jTable1.getValueAt(selected, 10);
        int id = app.Retorna_id_livro(Titulo, Genero, ISBN, Editora, Integer.parseInt(Ano), Autor, Integer.parseInt(Quant), Integer.parseInt(Num_page), Prat, Integer.parseInt(Linha), Integer.parseInt(Coluna));
        if (app.Remover_livro(id) && id != 0) {
            System.out.println("Livro Removido");
            try {
                Preencher_tabela("");
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceLivros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            System.out.println("Livro nao encontrado!!!");
        }
    }//GEN-LAST:event_BtnApagarActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        BtnApagar.setEnabled(true);
        BtnAtualizar.setEnabled(true);
    }//GEN-LAST:event_jTable1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfaceLivros().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(InterfaceLivros.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public static void Preencher_tabela(String word) throws SQLException {
        Limpar_tabela();
        ResultSet IDSelect = app.Listar_livros(word);
        while(IDSelect.next()) {
            String[] linha = {IDSelect.getString("Titulo"),
            IDSelect.getString("Genero"), IDSelect.getString("ISBN"),
            IDSelect.getString("Editora"), IDSelect.getString("Autor"),
            Integer.toString(IDSelect.getInt("AnoPublicacao")), Integer.toString(IDSelect.getInt("Numero_paginas")), Integer.toString(IDSelect.getInt("QuantidadeDisponivel")),
            IDSelect.getString("Nome_Prateleira"), Integer.toString(IDSelect.getInt("linha")),
            Integer.toString(IDSelect.getInt("coluna"))};
            modelo.addRow(linha);
        }
    }
    
    private static void Limpar_tabela() {
        int n = modelo.getRowCount();
        for(int i=n-1; i>=0;i--) {
            modelo.removeRow(i);
        }
    }
    
    public static Implementacao app = new Implementacao();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnApagar;
    private javax.swing.JToggleButton BtnAtualizar;
    private javax.swing.JToggleButton BtnCadastrar;
    private javax.swing.JTextField TXTShearch;
    private javax.swing.JToggleButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
